version: "3.1"

services:
  webapp:
    container_name: cst-webapp-dev
    environment:
      - NODE_ENV=development
    ports:
      - "2000:80"

  api:
    container_name: cst-api-dev
    volumes:
      - ./api/jwt.key.pub.example:/var/api/jwt.key.pub
      - ./api:/var/api
    environment:
      - NODE_ENV=development
    command: yarn start
    ports:
      - "2001:80"
      - "9222:9222"

  auth:
    container_name: cst-auth-dev
    volumes:
      - ./api/jwt.key.pub.example:/var/api/jwt.key.pub
      - ./api:/var/api
    environment:
      - NODE_ENV=development
    command: yarn start:auth
    ports:
      - "2002:80"
      - "9223:9223"

secrets:
  jwt.key:
    file: ./secrets/jwt.key.example
