version: "3"

services:
  web:
    container_name: cst-web-dev
    image: cst-web-dev
    volumes:
      - ./server:/var/server
    environment:
      - NODE_ENV=development
      - REACT_APP_API_ROOT=http://localhost:5050/
    command: yarn start
