version: "3.1"

services:
  webapp:
    container_name: cst-webapp-dev
    image: cst-webapp-dev
    environment:
      - NODE_ENV=development
      - REACT_APP_API_ROOT=http://localhost:2001/

  api:
    container_name: cst-api-dev
    image: cst-api-dev
    volumes:
      - ./api/jwt.key.pub.example:/var/api/jwt.key.pub
      - ./api:/var/api
    environment:
      - NODE_ENV=development
    command: yarn start
    ports:
      - "9222:9222"

  auth:
    container_name: cst-auth-dev
    image: cst-auth-dev
    volumes:
      - ./api/jwt.key.pub.example:/var/api/jwt.key.pub
      - ./api:/var/api
    environment:
      - NODE_ENV=development
    command: yarn start:auth
    ports:
      - "9223:9223"

networks:
  default:
    driver: bridge
  auth:
    driver: bridge

secrets:
  jwt.key:
    file: ./secrets/jwt.key.example
