version: "3"

services:
  webapp:
    container_name: cst-webapp-dev
    image: cst-webapp-dev
    environment:
      - NODE_ENV=development
      - REACT_APP_API_ROOT=http://localhost:2001/

  api:
    container_name: cst-api-dev
    image: cst-api-dev
    volumes:
      - ./api:/var/api
    environment:
      - NODE_ENV=development
    command: yarn start
    ports:
      - "9222:9222"
